import { RoomType, RewardType, GOLD_REWARDS, SACRIFICE_TIER_WEIGHTS, VaultCategory, VAULT_REWARDS, MAX_REWARD_REROLL, getBalancedProbability } from '../../config/dungeonConfig';
import { CoreId, FormId, PrefixId, SuffixId, CORE_REGISTRY, FORM_REGISTRY, PREFIX_REGISTRY, SUFFIX_REGISTRY } from '../../config/spellComponents';
import { PlayerProgression } from './PlayerProgression';
export interface RewardChoice { type: RewardType; id: CoreId | FormId | PrefixId | SuffixId; displayName: string; description: string; categoryLabel: string; categoryColor: number; visualConfig?: any; }
export interface RewardBundle { gold: Reward; choices: RewardChoice[]; category: 'core' | 'form' | 'prefix' | 'suffix' | 'none'; }
export class RewardGenerator {
  static generateNormalRewards(prog: PlayerProgression, layerIndex: number): RewardBundle { const gold = RewardGenerator.goldReward(GOLD_REWARDS.normal.min, GOLD_REWARDS.normal.max); const { choices, category } = RewardGenerator.generateCoreOrFormChoices(prog, 2); return { gold, choices, category }; }
  static generateEliteRewards(prog: PlayerProgression, layerIndex: number): RewardBundle { const gold = RewardGenerator.goldReward(GOLD_REWARDS.elite.min, GOLD_REWARDS.elite.max); const { choices, category } = RewardGenerator.generatePrefixOrSuffixChoices(prog, 3); return { gold, choices, category }; }
  static generateSinBossRewards(prog: PlayerProgression): RewardBundle { return { gold: RewardGenerator.goldReward(GOLD_REWARDS.sinBoss.min, GOLD_REWARDS.sinBoss.max), choices: [], category: 'none' }; }
  static generateDevilRewards(prog: PlayerProgression): RewardBundle { return { gold: RewardGenerator.goldReward(GOLD_REWARDS.devil.min, GOLD_REWARDS.devil.max), choices: [], category: 'none' }; }
  static generateVaultRewards(category: VaultCategory, prog: PlayerProgression): RewardBundle { switch (category) { case VaultCategory.FOUNDATION: { const { choices, category: cat } = RewardGenerator.generateCoreOrFormChoices(prog, 2); return { gold: RewardGenerator.goldReward(0, 0), choices, category: cat }; } case VaultCategory.ARSENAL: { const { choices, category: cat } = RewardGenerator.generatePrefixOrSuffixChoices(prog, 3); return { gold: RewardGenerator.goldReward(0, 0), choices, category: cat }; } case VaultCategory.FORTUNE: return { gold: RewardGenerator.goldReward(VAULT_REWARDS[VaultCategory.FORTUNE].goldMin, VAULT_REWARDS[VaultCategory.FORTUNE].goldMax), choices: [], category: 'none' }; } }
  static rollSacrificeTier(): 'common' | 'rare' | 'epic' { const total = SACRIFICE_TIER_WEIGHTS.common + SACRIFICE_TIER_WEIGHTS.rare + SACRIFICE_TIER_WEIGHTS.epic; const roll = Math.random() * total; if (roll < SACRIFICE_TIER_WEIGHTS.common) return 'common'; if (roll < SACRIFICE_TIER_WEIGHTS.common + SACRIFICE_TIER_WEIGHTS.rare) return 'rare'; return 'epic'; }
  static generateSacrificeReward(tier: 'common' | 'rare' | 'epic', prog: PlayerProgression): RewardBundle | null { switch (tier) { case 'common': { const { choices, category } = RewardGenerator.generateCoreOrFormChoices(prog, 2); return { gold: RewardGenerator.goldReward(0, 0), choices, category }; } case 'rare': { const { choices, category } = RewardGenerator.generatePrefixOrSuffixChoices(prog, 3); return { gold: RewardGenerator.goldReward(0, 0), choices, category }; } case 'epic': return { gold: RewardGenerator.goldReward(0, 0), choices: [{ type: RewardType.SIN_RELIC, id: 'SIN_RELIC' as any, displayName: 'Sin Relic', description: 'A powerful active ability born of sacrifice.', categoryLabel: 'SIN RELIC', categoryColor: 0xff4466 }], category: 'none' }; } }
  static generateCoreOrFormChoices(prog: PlayerProgression, count: number): { choices: RewardChoice[]; category: 'core' | 'form' } { const uc = prog.getUnownedCores(), uf = prog.getUnownedForms(); if (uc.length === 0 && uf.length === 0) return { choices: [], category: 'core' }; if (uc.length === 0) return { choices: RewardGenerator.buildFormChoices(uf, count), category: 'form' }; if (uf.length === 0) return { choices: RewardGenerator.buildCoreChoices(uc, count), category: 'core' }; const cc = prog.getCoreCount(), fc = prog.getFormCount(); const diff = Math.abs(cc - fc); const mp = getBalancedProbability(diff); let cp: number; if (cc > fc) cp = mp; else if (fc > cc) cp = 1 - mp; else cp = 0.5; if (Math.random() < cp) return { choices: RewardGenerator.buildCoreChoices(uc, count), category: 'core' }; else return { choices: RewardGenerator.buildFormChoices(uf, count), category: 'form' }; }
  static generatePrefixOrSuffixChoices(prog: PlayerProgression, count: number): { choices: RewardChoice[]; category: 'prefix' | 'suffix' } { const up = prog.getUnownedPrefixes(), us = prog.getUnownedSuffixes(); if (up.length === 0 && us.length === 0) return { choices: [], category: 'prefix' }; if (up.length === 0) return { choices: RewardGenerator.buildSuffixChoices(us, count), category: 'suffix' }; if (us.length === 0) return { choices: RewardGenerator.buildPrefixChoices(up, count), category: 'prefix' }; const pc = prog.getPrefixCount(), sc = prog.getSuffixCount(); const diff = Math.abs(pc - sc); const mp = getBalancedProbability(diff); let pp: number; if (pc > sc) pp = mp; else if (sc > pc) pp = 1 - mp; else pp = 0.5; if (Math.random() < pp) return { choices: RewardGenerator.buildPrefixChoices(up, count), category: 'prefix' }; else return { choices: RewardGenerator.buildSuffixChoices(us, count), category: 'suffix' }; }
  private static buildCoreChoices(unowned: CoreId[], count: number): RewardChoice[] { const s = [...unowned].sort(() => Math.random() - 0.5).slice(0, Math.min(count, unowned.length)); return s.map(id => { const r = CORE_REGISTRY[id]; return { type: RewardType.CORE, id, displayName: r?.displayName || id, description: r?.description || '', categoryLabel: 'CORE', categoryColor: 0xff8844, visualConfig: r?.visual }; }); }
  private static buildFormChoices(unowned: FormId[], count: number): RewardChoice[] { const s = [...unowned].sort(() => Math.random() - 0.5).slice(0, Math.min(count, unowned.length)); return s.map(id => { const r = FORM_REGISTRY[id]; return { type: RewardType.FORM, id, displayName: r?.displayName || id, description: r?.description || '', categoryLabel: 'FORM', categoryColor: 0x8888ff }; }); }
  private static buildPrefixChoices(unowned: PrefixId[], count: number): RewardChoice[] { const s = [...unowned].sort(() => Math.random() - 0.5).slice(0, Math.min(count, unowned.length)); return s.map(id => { const r = PREFIX_REGISTRY[id]; return { type: RewardType.PREFIX, id, displayName: r?.displayName || id, description: r?.description || '', categoryLabel: 'PREFIX', categoryColor: 0x88cc88 }; }); }
  private static buildSuffixChoices(unowned: SuffixId[], count: number): RewardChoice[] { const s = [...unowned].sort(() => Math.random() - 0.5).slice(0, Math.min(count, unowned.length)); return s.map(id => { const r = SUFFIX_REGISTRY[id]; return { type: RewardType.SUFFIX, id, displayName: r?.displayName || id, description: r?.description || '', categoryLabel: 'SUFFIX', categoryColor: 0xccaa66 }; }); }
  static goldReward(min: number, max: number): Reward { const amount = Math.floor(Math.random() * (max - min + 1)) + min; return { type: RewardType.GOLD, amount, displayName: `${amount} Gold`, description: 'Currency for the shop.', isNew: false }; }
}
export interface Reward { type: RewardType; id?: string; amount?: number; displayName: string; description: string; isNew: boolean; }
