import Phaser from 'phaser';
import { VisualConfig } from '../config/spellComponents';
export class PrefixVisuals {
  static renderHomingIndicator(scene: Phaser.Scene, projX: number, projY: number, targetX: number, targetY: number, visual: VisualConfig): void { const dist = Phaser.Math.Distance.Between(projX, projY, targetX, targetY); const angle = Phaser.Math.Angle.Between(projX, projY, targetX, targetY); const md = Math.min(dist * 0.6, 40); const mx = projX + Math.cos(angle) * md, my = projY + Math.sin(angle) * md; const m = scene.add.rectangle(mx, my, 4, 4, visual.glowColor, 0.4).setDepth(11).setAngle(45); scene.tweens.add({ targets: m, alpha: 0, scaleX: 0.2, scaleY: 0.2, duration: 150, onComplete: () => m.destroy() }); }
  static renderHomingTrail(scene: Phaser.Scene, x: number, y: number, visual: VisualConfig): void { const d = scene.add.circle(x, y, 1.5, visual.glowColor, 0.5).setDepth(7); scene.tweens.add({ targets: d, alpha: 0, duration: 300, onComplete: () => d.destroy() }); }
  static renderSplitMoment(scene: Phaser.Scene, x: number, y: number, visual: VisualConfig, splitCount: number, baseAngle: number, spreadDeg: number): void { const f = scene.add.circle(x, y, 8, 0xffffff, 0.7).setDepth(26); scene.tweens.add({ targets: f, scaleX: 2.5, scaleY: 2.5, alpha: 0, duration: 180, onComplete: () => f.destroy() }); const r = scene.add.circle(x, y, 5, 0, 0).setDepth(25).setStrokeStyle(2, visual.color, 0.6); scene.tweens.add({ targets: r, scaleX: 4, scaleY: 4, alpha: 0, duration: 250, onComplete: () => r.destroy() }); const sr = Phaser.Math.DegToRad(spreadDeg); for (let i = 0; i < splitCount; i++) { const fr = splitCount === 1 ? 0 : (i / (splitCount - 1)) - 0.5; const a = baseAngle + fr * sr * 2; const ll = 25; const ex = x + Math.cos(a) * ll, ey = y + Math.sin(a) * ll; const sl = scene.add.line(0, 0, x, y, ex, ey, visual.glowColor, 0.5).setOrigin(0, 0).setLineWidth(1.5).setDepth(25); scene.tweens.add({ targets: sl, alpha: 0, duration: 200, delay: 50, onComplete: () => sl.destroy() }); const dt = scene.add.circle(ex, ey, 3, visual.color, 0.7).setDepth(25); scene.tweens.add({ targets: dt, x: x + Math.cos(a) * ll * 1.5, y: y + Math.sin(a) * ll * 1.5, alpha: 0, duration: 200, onComplete: () => dt.destroy() }); } }
  static renderGreaterCastEffect(scene: Phaser.Scene, x: number, y: number, visual: VisualConfig, radius: number): void { const pr = scene.add.circle(x, y, radius * 0.3, 0, 0).setDepth(24).setStrokeStyle(2.5, visual.glowColor, 0.5); scene.tweens.add({ targets: pr, scaleX: 3, scaleY: 3, alpha: 0, duration: 400, ease: 'Power2', onComplete: () => pr.destroy() }); const f = scene.add.circle(x, y, radius * 0.15, 0xffffff, 0.4).setDepth(25); scene.tweens.add({ targets: f, scaleX: 4, scaleY: 4, alpha: 0, duration: 250, onComplete: () => f.destroy() }); const t = scene.add.text(x, y - radius - 10, '▲ GREATER', { fontFamily: '"Courier New", monospace', fontSize: '9px', color: '#' + visual.glowColor.toString(16).padStart(6, '0'), fontStyle: 'bold' }).setOrigin(0.5).setDepth(30).setAlpha(0.7); scene.tweens.add({ targets: t, y: t.y - 12, alpha: 0, duration: 800, onComplete: () => t.destroy() }); }
  static renderGreaterOrbAura(scene: Phaser.Scene, x: number, y: number, visual: VisualConfig, radius: number): Phaser.GameObjects.Arc { return scene.add.circle(x, y, radius + 4, visual.color, 0.06).setDepth(6).setStrokeStyle(0.5, visual.glowColor, 0.15); }
  static renderExpandingParticle(scene: Phaser.Scene, x: number, y: number, currentScale: number, visual: VisualConfig): void { const a = Math.random() * Math.PI * 2; const d = currentScale * 12; const px = x + Math.cos(a) * d, py = y + Math.sin(a) * d; const p = scene.add.circle(px, py, 1.5, visual.glowColor, 0.4).setDepth(7); scene.tweens.add({ targets: p, x: px + Math.cos(a) * 8, y: py + Math.sin(a) * 8, alpha: 0, scaleX: 2, scaleY: 2, duration: 200, onComplete: () => p.destroy() }); }
  static renderReturnMoment(scene: Phaser.Scene, x: number, y: number, visual: VisualConfig, returnAngle: number): void { const f = scene.add.circle(x, y, 10, visual.glowColor, 0.6).setDepth(25); scene.tweens.add({ targets: f, scaleX: 2, scaleY: 2, alpha: 0, duration: 200, onComplete: () => f.destroy() }); const al = 20; const ax = x + Math.cos(returnAngle) * al, ay = y + Math.sin(returnAngle) * al; const ar = scene.add.line(0, 0, x, y, ax, ay, visual.color, 0.6).setOrigin(0, 0).setLineWidth(2).setDepth(25); scene.tweens.add({ targets: ar, alpha: 0, duration: 400, onComplete: () => ar.destroy() }); const t = scene.add.text(x, y - 18, '↩ RETURN', { fontFamily: '"Courier New", monospace', fontSize: '8px', color: '#' + visual.glowColor.toString(16).padStart(6, '0') }).setOrigin(0.5).setDepth(30).setAlpha(0.6); scene.tweens.add({ targets: t, y: t.y - 10, alpha: 0, duration: 600, onComplete: () => t.destroy() }); }
  static renderReturnTrail(scene: Phaser.Scene, x: number, y: number, visual: VisualConfig): void { for (let i = 0; i < 2; i++) { const d = scene.add.circle(x + (Math.random() - 0.5) * 6, y + (Math.random() - 0.5) * 6, 2, visual.trailColor, 0.4).setDepth(7); scene.tweens.add({ targets: d, alpha: 0, scaleX: 0.5, scaleY: 0.5, duration: 250 + Math.random() * 100, onComplete: () => d.destroy() }); } }
  static renderPierceMoment(scene: Phaser.Scene, projX: number, projY: number, enemyX: number, enemyY: number, visual: VisualConfig, pierceCount: number, maxPierce: number): void { const a = Phaser.Math.Angle.Between(projX, projY, enemyX, enemyY); const entryX = enemyX - Math.cos(a) * 12, entryY = enemyY - Math.sin(a) * 12; const entry = scene.add.circle(entryX, entryY, 4, visual.glowColor, 0.6).setDepth(25); scene.tweens.add({ targets: entry, alpha: 0, scaleX: 2, scaleY: 2, duration: 150, onComplete: () => entry.destroy() }); const exitX = enemyX + Math.cos(a) * 12, exitY = enemyY + Math.sin(a) * 12; const exit = scene.add.circle(exitX, exitY, 4, visual.glowColor, 0.6).setDepth(25); scene.tweens.add({ targets: exit, alpha: 0, scaleX: 2, scaleY: 2, duration: 150, delay: 30, onComplete: () => exit.destroy() }); const tl = scene.add.line(0, 0, entryX, entryY, exitX, exitY, visual.color, 0.5).setOrigin(0, 0).setLineWidth(1.5).setDepth(25); scene.tweens.add({ targets: tl, alpha: 0, duration: 250, onComplete: () => tl.destroy() }); const remaining = maxPierce - pierceCount; if (remaining >= 0) { const t = scene.add.text(enemyX, enemyY - 16, `⟫ ${remaining}`, { fontFamily: '"Courier New", monospace', fontSize: '8px', color: '#' + visual.glowColor.toString(16).padStart(6, '0') }).setOrigin(0.5).setDepth(30).setAlpha(0.6); scene.tweens.add({ targets: t, y: t.y - 8, alpha: 0, duration: 500, onComplete: () => t.destroy() }); } }
  static renderPiercingTrail(scene: Phaser.Scene, x: number, y: number, vx: number, vy: number, visual: VisualConfig): void { const a = Math.atan2(vy, vx); const t = scene.add.ellipse(x, y, 6, 2, visual.trailColor, 0.5).setDepth(7).setAngle(Phaser.Math.RadToDeg(a)); scene.tweens.add({ targets: t, alpha: 0, scaleX: 2, scaleY: 0.5, duration: 200, onComplete: () => t.destroy() }); }
}
