import Phaser from 'phaser';
import { Enemy } from '../entities/Enemy';
import { CHAIN_ARC_SEGMENTS, CHAIN_ARC_OFFSET, CHAIN_ARC_COLOR, CHAIN_ARC_GLOW_COLOR, CHAIN_ARC_WIDTH, CHAIN_ARC_GLOW_WIDTH, CHAIN_ARC_DURATION, CHAIN_DELAY_BETWEEN, CHAIN_HIT_FLASH_COLOR, CHAIN_HIT_FLASH_RADIUS } from '../config/constants';
export class LightningChainSystem {
  private scene: Phaser.Scene;
  constructor(scene: Phaser.Scene) { this.scene = scene; }
  executeChain(source: Enemy, allEnemies: Enemy[], maxTargets: number, chainRange: number, baseDamage: number): void { const hitSet: Set<Enemy> = new Set(); hitSet.add(source); this.showHitFlash(source); this.chainStep(source, allEnemies, hitSet, maxTargets - 1, chainRange, baseDamage, 0); }
  private chainStep(current: Enemy, allEnemies: Enemy[], hitSet: Set<Enemy>, chainsRemaining: number, chainRange: number, baseDamage: number, hopIndex: number): void { if (chainsRemaining <= 0) return; let closest: Enemy | null = null, closestDist = Infinity; for (const enemy of allEnemies) { if (!enemy.alive || hitSet.has(enemy)) continue; const dist = Phaser.Math.Distance.Between(current.sprite.x, current.sprite.y, enemy.sprite.x, enemy.sprite.y); if (dist <= chainRange && dist < closestDist) { closestDist = dist; closest = enemy; } } if (!closest) return; hitSet.add(closest); const nextTarget = closest; this.scene.time.delayedCall(CHAIN_DELAY_BETWEEN * (hopIndex + 1), () => { if (!nextTarget.alive) return; this.drawLightningArc(current.sprite.x, current.sprite.y, nextTarget.sprite.x, nextTarget.sprite.y); this.showHitFlash(nextTarget); const dm = Math.pow(0.7, hopIndex + 1); nextTarget.takeDamage(Math.round(baseDamage * dm)); this.chainStep(nextTarget, allEnemies, hitSet, chainsRemaining - 1, chainRange, baseDamage, hopIndex + 1); }); }
  private drawLightningArc(x1: number, y1: number, x2: number, y2: number): void { const dx = x2 - x1, dy = y2 - y1, dist = Math.sqrt(dx * dx + dy * dy); const dirX = dx / dist, dirY = dy / dist, perpX = -dirY, perpY = dirX; const points: { x: number; y: number }[] = [{ x: x1, y: y1 }]; for (let i = 1; i < CHAIN_ARC_SEGMENTS; i++) { const t = i / CHAIN_ARC_SEGMENTS; const mf = Math.sin(t * Math.PI); const offset = (Math.random() * 2 - 1) * CHAIN_ARC_OFFSET * mf; points.push({ x: x1 + dx * t + perpX * offset, y: y1 + dy * t + perpY * offset }); } points.push({ x: x2, y: y2 }); const gg = this.scene.add.graphics().setDepth(20); gg.lineStyle(CHAIN_ARC_GLOW_WIDTH, CHAIN_ARC_GLOW_COLOR, 0.3); gg.beginPath(); gg.moveTo(points[0].x, points[0].y); for (let i = 1; i < points.length; i++) gg.lineTo(points[i].x, points[i].y); gg.strokePath(); const cg = this.scene.add.graphics().setDepth(21); cg.lineStyle(CHAIN_ARC_WIDTH, CHAIN_ARC_COLOR, 0.9); cg.beginPath(); cg.moveTo(points[0].x, points[0].y); for (let i = 1; i < points.length; i++) cg.lineTo(points[i].x, points[i].y); cg.strokePath(); this.scene.tweens.add({ targets: [gg, cg], alpha: 0, duration: CHAIN_ARC_DURATION, ease: 'Power2', onComplete: () => { gg.destroy(); cg.destroy(); } }); }
  private showHitFlash(enemy: Enemy): void { if (!enemy.sprite.active) return; const flash = this.scene.add.circle(enemy.sprite.x, enemy.sprite.y, CHAIN_HIT_FLASH_RADIUS, CHAIN_HIT_FLASH_COLOR, 0.7).setDepth(23); this.scene.tweens.add({ targets: flash, alpha: 0, scaleX: 2.5, scaleY: 2.5, duration: 250, ease: 'Power2', onComplete: () => flash.destroy() }); const core = this.scene.add.circle(enemy.sprite.x, enemy.sprite.y, 6, 0xffffff, 0.8).setDepth(24); this.scene.tweens.add({ targets: core, alpha: 0, scaleX: 3, scaleY: 3, duration: 180, ease: 'Power3', onComplete: () => core.destroy() }); enemy.sprite.setTint(CHAIN_ARC_COLOR); this.scene.time.delayedCall(120, () => { if (enemy.sprite.active) enemy.sprite.clearTint(); }); }
}
