import { CoreId, FormId, PrefixId, SuffixId, CoreComponent, FormComponent, PrefixComponent, SuffixComponent, getCore, getForm, getPrefix, getSuffix, getAllPrefixIds, getAllSuffixIds, getAllFormIds, CORE_FORM_RESTRICTIONS } from '../config/spellComponents';
export interface ValidationError { field: 'core' | 'form' | 'prefix' | 'suffix' | 'combination'; message: string; suggestion?: string; }
export interface ValidationResult { valid: boolean; errors: ValidationError[]; core: CoreComponent | null; form: FormComponent | null; prefix: PrefixComponent | null; suffix: SuffixComponent | null; }
export class SpellValidator {
  static validate(coreId: CoreId | null, formId: FormId | null, prefixId?: PrefixId | null, suffixId?: SuffixId | null): ValidationResult { const errors: ValidationError[] = []; let core: CoreComponent | null = null, form: FormComponent | null = null, prefix: PrefixComponent | null = null, suffix: SuffixComponent | null = null; if (!coreId) errors.push({ field: 'core', message: 'Missing Core.' }); else { core = getCore(coreId); if (!core) errors.push({ field: 'core', message: `Unknown Core: "${coreId}".` }); } if (!formId) errors.push({ field: 'form', message: 'Missing Form.' }); else { form = getForm(formId); if (!form) errors.push({ field: 'form', message: `Unknown Form: "${formId}".` }); } if (prefixId) { prefix = getPrefix(prefixId); if (!prefix) errors.push({ field: 'prefix', message: `Unknown Prefix: "${prefixId}".` }); } if (suffixId) { suffix = getSuffix(suffixId); if (!suffix) errors.push({ field: 'suffix', message: `Unknown Suffix: "${suffixId}".` }); } if (!core || !form) return { valid: false, errors, core, form, prefix, suffix }; if (prefix && form) { if (prefix.compatibleForms !== 'all' && !(prefix.compatibleForms as FormId[]).includes(form.id)) errors.push({ field: 'prefix', message: `${prefix.displayName} cannot be used with ${form.displayName}.` }); if (form.compatiblePrefixes !== 'all' && !(form.compatiblePrefixes as PrefixId[]).includes(prefix.id)) errors.push({ field: 'combination', message: `${form.displayName} does not support ${prefix.displayName}.` }); } if (suffix && form) { if (suffix.compatibleForms !== 'all' && !(suffix.compatibleForms as FormId[]).includes(form.id)) errors.push({ field: 'suffix', message: `${suffix.displayName} cannot be used with ${form.displayName}.` }); if (form.compatibleSuffixes !== 'all' && !(form.compatibleSuffixes as SuffixId[]).includes(suffix.id)) errors.push({ field: 'combination', message: `${form.displayName} does not support ${suffix.displayName}.` }); } if (core && form) { const r = CORE_FORM_RESTRICTIONS.find(r => r.coreId === core!.id && r.formId === form!.id); if (r) errors.push({ field: 'combination', message: r.reason, suggestion: r.suggestion }); } if (prefix && core && prefix.compatibleCores !== 'all' && !(prefix.compatibleCores as CoreId[]).includes(core.id)) errors.push({ field: 'prefix', message: `${prefix.displayName} cannot be used with ${core.displayName}.` }); if (suffix && core && suffix.compatibleCores !== 'all' && !(suffix.compatibleCores as CoreId[]).includes(core.id)) errors.push({ field: 'suffix', message: `${suffix.displayName} cannot be used with ${core.displayName}.` }); return { valid: errors.length === 0, errors, core, form, prefix, suffix }; }
  static getCompatiblePrefixes(formId: FormId): PrefixComponent[] { const form = getForm(formId); if (!form) return []; return getAllPrefixIds().map(id => getPrefix(id)!).filter(p => { if (p.compatibleForms !== 'all' && !(p.compatibleForms as FormId[]).includes(formId)) return false; if (form.compatiblePrefixes !== 'all' && !(form.compatiblePrefixes as PrefixId[]).includes(p.id)) return false; return true; }); }
  static getCompatibleSuffixes(formId: FormId): SuffixComponent[] { const form = getForm(formId); if (!form) return []; return getAllSuffixIds().map(id => getSuffix(id)!).filter(s => { if (s.compatibleForms !== 'all' && !(s.compatibleForms as FormId[]).includes(formId)) return false; if (form.compatibleSuffixes !== 'all' && !(form.compatibleSuffixes as SuffixId[]).includes(s.id)) return false; return true; }); }
  static isValid(coreId: CoreId | null, formId: FormId | null, prefixId?: PrefixId | null, suffixId?: SuffixId | null): boolean { if (!coreId || !formId) return false; return SpellValidator.validate(coreId, formId, prefixId, suffixId).valid; }
  static getFirstError(coreId: CoreId | null, formId: FormId | null, prefixId?: PrefixId | null, suffixId?: SuffixId | null): string { const r = SpellValidator.validate(coreId, formId, prefixId, suffixId); if (r.valid) return ''; return r.errors[0]?.message || 'Invalid spell.'; }
}
