import { CoreId, FormId, PrefixId, SuffixId, CoreComponent, FormComponent, PrefixComponent, SuffixComponent, StatusEffectConfig, VisualConfig, TargetingType, getCore, getForm, getPrefix, getSuffix, identifyWord, identifySuffix } from '../config/spellComponents';
import { SpellValidator } from './SpellValidator';
import { calcManaCost, calcCooldown, calcDamage } from '../config/formulas';
export interface Spell { name: string; displayName: string; core: CoreComponent; form: FormComponent; prefix: PrefixComponent | null; suffix: SuffixComponent | null; damage: number; manaCost: number; cooldown: number; statusEffect: StatusEffectConfig; targetingType: TargetingType; visual: VisualConfig; isEcho?: boolean; }
export interface BuildResult { success: boolean; spell: Spell | null; error: string; suggestion?: string; }
export type ParseResult = BuildResult;
export class SpellBuilder {
  static build(coreId: CoreId, formId: FormId, prefixId?: PrefixId | null, suffixId?: SuffixId | null): BuildResult { const v = SpellValidator.validate(coreId, formId, prefixId, suffixId); if (!v.valid) { const e = v.errors[0]; return { success: false, spell: null, error: e.message, suggestion: e.suggestion }; } return { success: true, spell: SpellBuilder.assemble(v.core!, v.form!, v.prefix, v.suffix), error: '' }; }
  static parseAndBuild(raw: string): ParseResult { const cleaned = raw.toUpperCase().trim(); if (cleaned === '') return { success: false, spell: null, error: 'Enter a spell name.' }; const words = cleaned.split(/\s+/); if (words.length > 6) return { success: false, spell: null, error: 'Too many words.' }; let suffixId: SuffixId | null = null; let rw = [...words]; if (rw.length >= 2) { const l2 = rw.slice(-2).join(' '); const m = identifySuffix(l2); if (m) { suffixId = m.id as SuffixId; rw = rw.slice(0, -2); } } if (!suffixId && rw.length >= 1) { const l1 = rw[rw.length - 1]; const m = identifySuffix(l1); if (m) { suffixId = m.id as SuffixId; rw = rw.slice(0, -1); } } if (rw.length < 2) { if (rw.length === 1) { const m = identifyWord(rw[0]); if (m?.type === 'core') return { success: false, spell: null, error: 'Missing Form.' }; if (m?.type === 'form') return { success: false, spell: null, error: 'Missing Core.' }; if (m?.type === 'prefix') return { success: false, spell: null, error: 'Missing Core and Form.' }; } if (rw.length === 0 && suffixId) return { success: false, spell: null, error: 'Missing Core and Form.' }; return { success: false, spell: null, error: 'Need at least Core + Form.' }; } if (rw.length > 3) return { success: false, spell: null, error: 'Too many words before suffix.' }; const id = rw.map(w => ({ word: w, match: identifyWord(w) })); for (const item of id) { if (!item.match) return { success: false, spell: null, error: `Unknown word: "${item.word}".` }; } const cores = id.filter(i => i.match!.type === 'core'); const forms = id.filter(i => i.match!.type === 'form'); const prefixes = id.filter(i => i.match!.type === 'prefix'); if (cores.length === 0) return { success: false, spell: null, error: 'Missing Core.' }; if (cores.length > 1) return { success: false, spell: null, error: 'Only one Core allowed.' }; if (forms.length === 0) return { success: false, spell: null, error: 'Missing Form.' }; if (forms.length > 1) return { success: false, spell: null, error: 'Only one Form allowed.' }; if (prefixes.length > 1) return { success: false, spell: null, error: 'Only one Prefix allowed.' }; return SpellBuilder.build(cores[0].match!.id as CoreId, forms[0].match!.id as FormId, prefixes.length > 0 ? prefixes[0].match!.id as PrefixId : null, suffixId); }
  private static assemble(core: CoreComponent, form: FormComponent, prefix: PrefixComponent | null, suffix: SuffixComponent | null): Spell { const np: string[] = []; if (prefix) np.push(prefix.displayName); np.push(core.displayName); np.push(form.displayName); if (suffix) np.push(suffix.displayName); const name = np.join(' '); const pef = prefix?.behavior.type === 'greater' ? prefix.behavior.extraDamageFlat : 0; const damage = calcDamage(core.baseDamage, form.damageMultiplier, prefix?.damageMultiplier ?? 1, pef, suffix?.damageMultiplier ?? 1); const manaCost = calcManaCost(core.manaCost, form.manaCost, prefix?.manaCost ?? 0, suffix?.manaCost ?? 0); const cooldown = calcCooldown(form.cooldown, prefix?.cooldownMultiplier ?? 1, suffix?.cooldownMultiplier ?? 1); const visual: VisualConfig = { ...core.visual }; if (prefix?.visual) { if (prefix.visual.color !== undefined) visual.color = prefix.visual.color; if (prefix.visual.glowColor !== undefined) visual.glowColor = prefix.visual.glowColor; if (prefix.visual.trailColor !== undefined) visual.trailColor = prefix.visual.trailColor; } if (suffix?.visual) { if (suffix.visual.color !== undefined) visual.color = suffix.visual.color; if (suffix.visual.glowColor !== undefined) visual.glowColor = suffix.visual.glowColor; if (suffix.visual.trailColor !== undefined) visual.trailColor = suffix.visual.trailColor; } return { name, displayName: name, core, form, prefix, suffix, damage, manaCost, cooldown, statusEffect: JSON.parse(JSON.stringify(core.statusEffect)), targetingType: form.targetingType, visual }; }
}
