import Phaser from 'phaser';
import { DamageSource, Enemy } from '../entities/Enemy';
import { ENEMY_RADIUS, BURN_TICK_INTERVAL, BURN_PARTICLE_INTERVAL, BURN_PARTICLE_COLORS, BURN_PARTICLE_SIZE_MIN, BURN_PARTICLE_SIZE_MAX, BURN_PARTICLE_LIFETIME, BURN_PARTICLE_RISE, SLOW_TINT, SLOW_RING_COLOR, SLOW_RING_ALPHA, SLOW_CRYSTAL_COUNT, SLOW_CRYSTAL_COLOR } from '../config/constants';
interface ActiveBurn { enemy: Enemy; damagePerSecond: number; remainingMs: number; tickTimer: Phaser.Time.TimerEvent; particleTimer: Phaser.Time.TimerEvent; particles: Phaser.GameObjects.Arc[]; source?: DamageSource; }
interface ActiveSlow { enemy: Enemy; slowPercent: number; remainingMs: number; expireTimer: Phaser.Time.TimerEvent; ring: Phaser.GameObjects.Arc; crystals: Phaser.GameObjects.Arc[]; crystalTween: Phaser.Tweens.Tween | null; }
export class StatusEffectSystem {
  private scene: Phaser.Scene; private activeBurns: Map<Enemy, ActiveBurn> = new Map(); private activeSlows: Map<Enemy, ActiveSlow> = new Map();
  constructor(scene: Phaser.Scene) { this.scene = scene; }
  applyBurn(enemy: Enemy, damagePerSecond: number, durationSeconds: number, source?: DamageSource): void { if (!enemy.alive) return; const totalMs = durationSeconds * 1000; this.flashEnemy(enemy, 0xff6600, 150); const existing = this.activeBurns.get(enemy); if (existing) { existing.remainingMs = totalMs; existing.source = source; if (damagePerSecond > existing.damagePerSecond) existing.damagePerSecond = damagePerSecond; return; } const particles: Phaser.GameObjects.Arc[] = []; const tickTimer = this.scene.time.addEvent({ delay: BURN_TICK_INTERVAL, callback: () => { const burn = this.activeBurns.get(enemy); if (!burn || !enemy.alive) { this.removeBurn(enemy); return; } const td = (burn.damagePerSecond * BURN_TICK_INTERVAL) / 1000; enemy.takeDamage(td, burn.source); this.flashEnemy(enemy, 0xff4400, 80); burn.remainingMs -= BURN_TICK_INTERVAL; if (burn.remainingMs <= 0) this.removeBurn(enemy); }, loop: true }); const particleTimer = this.scene.time.addEvent({ delay: BURN_PARTICLE_INTERVAL, callback: () => { const burn = this.activeBurns.get(enemy); if (!burn || !enemy.alive) return; this.spawnBurnParticle(enemy, particles); }, loop: true }); this.activeBurns.set(enemy, { enemy, damagePerSecond, remainingMs: totalMs, tickTimer, particleTimer, particles, source }); }
  private spawnBurnParticle(enemy: Enemy, particles: Phaser.GameObjects.Arc[]): void { const color = Phaser.Utils.Array.GetRandom(BURN_PARTICLE_COLORS); const size = Phaser.Math.Between(BURN_PARTICLE_SIZE_MIN, BURN_PARTICLE_SIZE_MAX); const ox = Phaser.Math.Between(-ENEMY_RADIUS, ENEMY_RADIUS); const oy = Phaser.Math.Between(Math.floor(-ENEMY_RADIUS * 0.5), Math.floor(ENEMY_RADIUS * 0.5)); const p = this.scene.add.circle(enemy.sprite.x + ox, enemy.sprite.y + oy, size, color, 0.8).setDepth(22); particles.push(p); this.scene.tweens.add({ targets: p, y: p.y - BURN_PARTICLE_RISE - Phaser.Math.Between(0, 8), alpha: 0, scaleX: { from: 1, to: 0.3 }, scaleY: { from: 1, to: 0.3 }, duration: BURN_PARTICLE_LIFETIME + Phaser.Math.Between(-50, 100), ease: 'Power1', onComplete: () => { p.destroy(); const idx = particles.indexOf(p); if (idx !== -1) particles.splice(idx, 1); } }); }
  private removeBurn(enemy: Enemy): void { const burn = this.activeBurns.get(enemy); if (!burn) return; burn.tickTimer.destroy(); burn.particleTimer.destroy(); for (const p of burn.particles) p.destroy(); burn.particles.length = 0; this.activeBurns.delete(enemy); }
  applySlow(enemy: Enemy, slowPercent: number, durationSeconds: number): void { if (!enemy.alive) return; const totalMs = durationSeconds * 1000; this.flashEnemy(enemy, 0x44ccff, 150); const existing = this.activeSlows.get(enemy); if (existing) { existing.expireTimer.destroy(); if (slowPercent > existing.slowPercent) { existing.slowPercent = slowPercent; enemy.setSpeedMultiplier(1 - slowPercent); } existing.remainingMs = totalMs; existing.expireTimer = this.scene.time.delayedCall(totalMs, () => { this.removeSlow(enemy); }); return; } enemy.setSpeedMultiplier(1 - slowPercent); enemy.sprite.setTint(SLOW_TINT); const ring = this.scene.add.circle(enemy.sprite.x, enemy.sprite.y, ENEMY_RADIUS + 6, SLOW_RING_COLOR, SLOW_RING_ALPHA).setDepth(8).setStrokeStyle(1, SLOW_RING_COLOR, 0.4); const crystals: Phaser.GameObjects.Arc[] = []; for (let i = 0; i < SLOW_CRYSTAL_COUNT; i++) { const a = (i / SLOW_CRYSTAL_COUNT) * Math.PI * 2; const cx = enemy.sprite.x + Math.cos(a) * (ENEMY_RADIUS + 8); const cy = enemy.sprite.y + Math.sin(a) * (ENEMY_RADIUS + 8); const crystal = this.scene.add.circle(cx, cy, 2, SLOW_CRYSTAL_COLOR, 0.7).setDepth(22); crystals.push(crystal); } const crystalTween = this.scene.tweens.addCounter({ from: 0, to: 360, duration: 2000, repeat: -1 }); const expireTimer = this.scene.time.delayedCall(totalMs, () => { this.removeSlow(enemy); }); this.activeSlows.set(enemy, { enemy, slowPercent, remainingMs: totalMs, expireTimer, ring, crystals, crystalTween }); }
  private removeSlow(enemy: Enemy): void { const slow = this.activeSlows.get(enemy); if (!slow) return; slow.expireTimer.destroy(); enemy.setSpeedMultiplier(1); if (enemy.sprite.active) enemy.sprite.clearTint(); slow.ring.destroy(); if (slow.crystalTween) slow.crystalTween.destroy(); for (const c of slow.crystals) c.destroy(); slow.crystals.length = 0; this.activeSlows.delete(enemy); }
  update(): void { for (const [enemy, slow] of this.activeSlows) { if (!enemy.alive) { this.removeSlow(enemy); continue; } slow.ring.setPosition(enemy.sprite.x, enemy.sprite.y); const tv = slow.crystalTween ? Number((slow.crystalTween as Phaser.Tweens.Tween).getValue() ?? 0) : 0; const ba = Phaser.Math.DegToRad(tv); for (let i = 0; i < slow.crystals.length; i++) { const a = ba + (i / slow.crystals.length) * Math.PI * 2; const or = ENEMY_RADIUS + 8; slow.crystals[i].setPosition(enemy.sprite.x + Math.cos(a) * or, enemy.sprite.y + Math.sin(a) * or); } } for (const [enemy] of this.activeBurns) { if (!enemy.alive) this.removeBurn(enemy); } }
  removeAllEffects(enemy: Enemy): void { this.removeBurn(enemy); this.removeSlow(enemy); }
  clearAll(): void { for (const [enemy] of this.activeBurns) this.removeBurn(enemy); for (const [enemy] of this.activeSlows) this.removeSlow(enemy); }
  private flashEnemy(enemy: Enemy, color: number, durationMs: number): void { if (!enemy.sprite.active) return; enemy.sprite.setTint(color); this.scene.time.delayedCall(durationMs, () => { if (!enemy.sprite.active) return; if (this.activeSlows.has(enemy)) enemy.sprite.setTint(SLOW_TINT); else enemy.sprite.clearTint(); }); }
}
