import Phaser from 'phaser';
import { DungeonState } from '../systems/dungeon/DungeonState';
import { DungeonGenerator } from '../systems/dungeon/DungeonGenerator';
import { RoomType, SIN_DEFINITIONS, getCombatConfig } from '../config/dungeonConfig';
import { ROOM_WIDTH, ROOM_HEIGHT } from '../config/constants';
import { uiText, applyTextShadow, createGlassPanel } from '../config/uiStyles';
import { RoomEnvironment } from '../visuals/environment/RoomEnvironment';
export class DungeonMapScene extends Phaser.Scene {
  private dungeon!: DungeonState;
  constructor() { super({ key: 'DungeonMapScene' }); }
  init(data?: { dungeon?: DungeonState }): void { if (data?.dungeon) this.dungeon = data.dungeon; else this.dungeon = DungeonGenerator.generateRun(); }
  create(): void { const cx = ROOM_WIDTH / 2; RoomEnvironment.createBackground(this, RoomType.NORMAL, this.dungeon.currentLayerIndex, this.dungeon.getCurrentLayer()?.sinId); if (!this.dungeon.runActive) { this.scene.start('RunOverScene', { dungeon: this.dungeon, victory: this.dungeon.runWon }); return; } const layer = this.dungeon.getCurrentLayer(); const room = this.dungeon.getCurrentRoom(); const layerNum = layer.layerIndex + 1; const sinName = layer.sinId ? SIN_DEFINITIONS[layer.sinId].displayName : 'The Devil'; const sinColor = layer.sinId ? SIN_DEFINITIONS[layer.sinId].color : 0xff0000; const sinHex = '#' + sinColor.toString(16).padStart(6, '0'); const headerT = this.add.text(cx, 28, `LAYER ${layerNum}`, uiText(20, '#d8ccf0', true)).setOrigin(0.5); applyTextShadow(headerT); this.add.text(cx, 52, `Domain of ${sinName}`, uiText(12, sinHex)).setOrigin(0.5); this.buildProgressBar(layer, 80); this.buildStatsBar(); if (!room.chosen && room.choice) this.showRoomChoice(room); else this.showRoomEntry(room); }
  private buildProgressBar(layer: any, y: number): void { const cx = ROOM_WIDTH / 2; const barW = Math.min(560, ROOM_WIDTH - 100); const roomCount = layer.rooms.length; const dotGap = barW / (roomCount - 1); const startX = cx - barW / 2; this.add.rectangle(cx, y, barW, 2, 0x3a2a5a, 0.3); const cc = layer.rooms.filter((r: any) => r.completed).length; if (cc > 0) this.add.rectangle(startX + dotGap * cc / 2, y, dotGap * cc, 2, 0x55cc55, 0.6); for (let i = 0; i < roomCount; i++) { const r = layer.rooms[i]; const dx = startX + i * dotGap; let color = 0x444466, size = 5, alpha = 0.3; if (r.completed) { color = 0x55cc55; size = 6; alpha = 0.8; } else if (r.isCurrent) { color = 0xffcc44; size = 8; alpha = 1; } this.add.circle(dx, y, size, color, alpha); const label = r.completed ? '✓' : `${i + 1}`; const lc = r.isCurrent ? '#ffcc44' : r.completed ? '#55cc55' : '#555577'; this.add.text(dx, y + 16, label, uiText(8, lc)).setOrigin(0.5); if (r.isCurrent) { const tn = this.getRoomLabel(r.chosen ? r.type : 'CHOOSE'); this.add.text(dx, y + 28, tn, uiText(7, '#ffcc44')).setOrigin(0.5); } } }
  private buildStatsBar(): void { const prog = this.dungeon.progression; const cx = ROOM_WIDTH / 2; const y = ROOM_HEIGHT - 28; this.add.text(cx, y, `HP ${prog.currentHp}/${prog.maxHp}  ·  Mana ${prog.maxMana}  ·  Gold ${prog.gold}  ·  C:${prog.getCoreCount()} F:${prog.getFormCount()} P:${prog.getPrefixCount()} S:${prog.getSuffixCount()}${prog.sinRelics.length > 0 ? '  ·  Relics: ' + prog.sinRelics.length : ''}`, uiText(9, '#667788')).setOrigin(0.5); }
  private showRoomChoice(room: any): void { const cx = ROOM_WIDTH / 2, cy = ROOM_HEIGHT / 2 + 10; const ct = this.add.text(cx, cy - 170, 'CHOOSE YOUR PATH', uiText(18, '#ccbbee', true)).setOrigin(0.5); applyTextShadow(ct); this.add.text(cx, cy - 145, `Room ${room.roomIndex + 1} of 7`, uiText(10, '#777799')).setOrigin(0.5); this.buildRoomCard(cx - 170, cy, room.choice.cardA, () => { this.dungeon.resolveChoice(room.choice.cardA); this.scene.restart({ dungeon: this.dungeon } as any); }); this.add.text(cx, cy, 'OR', uiText(16, '#555577', true)).setOrigin(0.5); this.buildRoomCard(cx + 170, cy, room.choice.cardB, () => { this.dungeon.resolveChoice(room.choice.cardB); this.scene.restart({ dungeon: this.dungeon } as any); }); }
  private showRoomEntry(room: any): void { const cx = ROOM_WIDTH / 2, cy = ROOM_HEIGHT / 2; const rc = this.getRoomColor(room.type); const rh = '#' + rc.toString(16).padStart(6, '0'); this.add.text(cx, cy - 100, `ROOM ${room.roomIndex + 1}`, uiText(12, '#8899aa')).setOrigin(0.5); this.add.text(cx, cy - 55, this.getRoomSymbol(room.type), uiText(40, rh)).setOrigin(0.5); const nt = this.add.text(cx, cy - 10, this.getRoomLabel(room.type), uiText(24, rh, true)).setOrigin(0.5); applyTextShadow(nt); this.add.text(cx, cy + 24, this.getRoomDesc(room.type), { ...uiText(11, '#8899aa'), align: 'center' }).setOrigin(0.5); const hint = this.getRewardHint(room.type); if (hint) this.add.text(cx, cy + 50, hint, uiText(10, '#667788')).setOrigin(0.5); const btn = createGlassPanel(this, cx, cy + 100, 220, 48, 10, 0.7); btn.setStrokeStyle(1.5, rc, 0.5).setInteractive({ useHandCursor: true }); const bt = this.add.text(cx, cy + 100, 'ENTER', uiText(16, rh, true)).setOrigin(0.5).setDepth(11); applyTextShadow(bt); btn.on('pointerover', () => btn.setFillStyle(0x161228, 0.85)); btn.on('pointerout', () => btn.setFillStyle(0x0c0a14, 0.7)); btn.on('pointerdown', () => this.enterRoom(room)); }
  private buildRoomCard(x: number, y: number, type: RoomType, onClick: () => void): void { const w = 240, h = 260; const color = this.getRoomColor(type); const hex = '#' + color.toString(16).padStart(6, '0'); const card = createGlassPanel(this, x, y, w, h, 10, 0.75); card.setStrokeStyle(1, color, 0.35).setInteractive({ useHandCursor: true }); this.add.text(x, y - 70, this.getRoomSymbol(type), uiText(36, hex)).setOrigin(0.5).setDepth(11); const nt = this.add.text(x, y - 20, this.getRoomLabel(type), uiText(18, hex, true)).setOrigin(0.5).setDepth(11); applyTextShadow(nt); this.add.text(x, y + 14, this.getRoomDesc(type), { ...uiText(10, '#8899aa'), align: 'center', wordWrap: { width: w - 30 } }).setOrigin(0.5).setDepth(11); const hint = this.getRewardHint(type); if (hint) { this.add.rectangle(x, y + 55, w - 30, 1, color, 0.15).setDepth(11); this.add.text(x, y + 70, hint, { ...uiText(9, '#667788'), align: 'center', wordWrap: { width: w - 30 } }).setOrigin(0.5).setDepth(11); } card.on('pointerover', () => { card.setStrokeStyle(2, color, 0.7); card.setFillStyle(0x161228, 0.85); }); card.on('pointerout', () => { card.setStrokeStyle(1, color, 0.35); card.setFillStyle(0x0c0a14, 0.75); }); card.on('pointerdown', onClick); }
  private enterRoom(room: any): void { const li = this.dungeon.currentLayerIndex; switch (room.type) { case RoomType.NORMAL: case RoomType.ELITE: case RoomType.SIN_BOSS: case RoomType.DEVIL: if (this.scene.isActive('HUDScene')) this.scene.stop('HUDScene'); this.scene.start('GameScene', { dungeon: this.dungeon, roomType: room.type, combatConfig: getCombatConfig(room.type, li) }); break; case RoomType.SHOP_REST: this.scene.start('ShopRestScene', { dungeon: this.dungeon }); break; case RoomType.SHRINE: this.scene.start('ShrineScene', { dungeon: this.dungeon }); break; case RoomType.VAULT: this.scene.start('VaultScene', { dungeon: this.dungeon }); break; case RoomType.SACRIFICE: this.scene.start('SacrificeScene', { dungeon: this.dungeon }); break; } }
  private getRoomLabel(type: RoomType | string): string { const l: Record<string, string> = { NORMAL: 'NORMAL', ELITE: 'ELITE', SHRINE: 'SHRINE', VAULT: 'VAULT', SACRIFICE: 'SACRIFICE', SHOP_REST: 'SHOP & REST', SIN_BOSS: 'SIN BOSS', DEVIL: 'THE DEVIL', CHOOSE: 'CHOOSE' }; return l[type] || String(type); }
  private getRoomColor(type: RoomType): number { const c: Record<string, number> = { NORMAL: 0x88aacc, ELITE: 0xff8844, SHRINE: 0xcc88ff, VAULT: 0xffcc44, SACRIFICE: 0xff4466, SHOP_REST: 0x44cc88, SIN_BOSS: 0xff4444, DEVIL: 0xff0000 }; return c[type] || 0x888888; }
  private getRoomSymbol(type: RoomType): string { const s: Record<string, string> = { NORMAL: '⚔', ELITE: '★', SHRINE: '✦', VAULT: '◆', SACRIFICE: '☠', SHOP_REST: '♦', SIN_BOSS: '◉', DEVIL: '◉' }; return s[type] || '?'; }
  private getRoomDesc(type: RoomType): string { const d: Record<string, string> = { NORMAL: 'Standard combat encounter', ELITE: 'Difficult combat encounter', SHRINE: 'A mysterious magical shrine', VAULT: 'Choose a guaranteed reward', SACRIFICE: 'Trade a component\nfor a chance at something greater', SHOP_REST: 'Buy upgrades and restore health', SIN_BOSS: 'Face the Sin of this domain', DEVIL: 'The final battle awaits' }; return d[type] || ''; }
  private getRewardHint(type: RoomType): string | null { const h: Record<string, string> = { NORMAL: 'Reward: Gold + Core or Form', ELITE: 'Reward: Gold + Prefix or Suffix', VAULT: 'Choose: Foundation / Arsenal / Fortune', SACRIFICE: 'Roll: Common / Rare / Epic', SIN_BOSS: 'Reward: Gold + Sin Relic' }; return h[type] || null; }
}
